resource_types:
  - name: rss-resource
    type: docker-image
    source:
      repository: suhlig/concourse-rss-resource
      tag: latest

resources:
  - name: nasa-image-of-the-day
    type: rss-resource
    source:
      url: https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss
  - name: nasa-git
    type: git
    source:
      uri: https://github.com/Evertras/concourseci-sandbox
      branch: master
  - name: docker-image
    type: docker-image
    source:
      repository: evertras/nasa-potd
      username: ((dockerhub.username))
      password: ((dockerhub.access-token))

jobs:
  - name: build-site
    plan:
      - get: nasa-image-of-the-day
        trigger: true
      - get: nasa-git
        trigger: true
      - task: gen-site
        config:
          inputs:
            - name: nasa-image-of-the-day
            - name: nasa-git
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: ubuntu
          run:
            path: "bash"
            args:
              - -exc
              - |
                mkdir -p ./generated-site/site
                ./nasa-git/nasa/gen-site.sh "$(cat nasa-image-of-the-day/title)" "$(cat nasa-image-of-the-day/description)" "$(cat nasa-image-of-the-day/link)" ${PWD}/generated-site
          outputs:
            - name: generated-site
      - put: docker-image
        params:
          build: generated-site

