resource_types:
  - name: rss-resource
    type: docker-image
    source:
      repository: suhlig/concourse-rss-resource
      tag: latest

resources:
  - name: nasa-image-of-the-day
    type: rss-resource
    source:
      url: https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss

jobs:
  - name: title-echo
    plan:
      - get: nasa-image-of-the-day
        trigger: true
      - task: build-daily-image
        config:
          inputs:
            - name: nasa-image-of-the-day
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: alpine
          run:
            path: cat
            args: [ "nasa-image-of-the-day/link" ]

