---
resources:
  - name: crudlib-git
    type: git
    icon: github
    source:
      uri: https://github.com/Evertras/concourseci-sandbox
      branch: master

  - name: golang-1.12.x-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: '1.12'

  - name: golang-1.13.x-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: '1.13'

  - name: golang-1.14.x-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: '1.14'

config-test: &config-test
  inputs:
    - name: crudlib-git
  platform: linux
  run:
    dir: crudlib-git/crudlib
    path: "go"
    args:
      - test
      - -race
      - .

config-lint: &config-lint
  inputs:
    - name: crudlib-git
  platform: linux
  run:
    dir: crudlib-git/crudlib
    path: "bash"
    args:
      - -exc
      # Make sure that go fmt doesn't have to do anything; if it did, then someone
      # didn't properly format their code!
      - '[[ -z "$(go fmt .)" ]]'

jobs:
  - name: test-1.12
    plan:
      - get: crudlib-git
        trigger: true
      - get: golang-1.12.x-image
      - task: test
        image: golang-1.12.x-image
        config:
          << : *config-test

  - name: test-1.13
    plan:
      - get: crudlib-git
        trigger: true
      - get: golang-1.13.x-image
      - task: test
        image: golang-1.13.x-image
        config:
          << : *config-test

  - name: test-1.14
    plan:
      - get: crudlib-git
        trigger: true
      - get: golang-1.14.x-image
      - task: test
        image: golang-1.14.x-image
        config:
          << : *config-test
      - task: lint
        image: golang-1.14.x-image
        config:
          << : *config-lint

